apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b51t7rz3e-nodejs
  janus-idp.io/tekton: b51t7rz3e-nodejs
  backstage.io/kubernetes-id: b51t7rz3e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b51t7rz3e-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
