apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b51t7rz3e-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b51t7rz3e-nodejs 
  name: b51t7rz3e-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: b51t7rz3e-nodejs 
